name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test  # update if you have tests, otherwise remove or comment

      - name: Build (optional)
        run: npm run build  # update or remove if not required

      - name: Deploy (placeholder)
        run: |
          echo "Deployment step goes here. Example: docker build and push."
          # Example Docker build:
          # docker build -t your-image-name .
          # echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          # docker tag your-image-name your-dockerhub-username/your-image-name:latest
          # docker push your-dockerhub-username/your-image-name:latest
